### ISSUE TITLE
Rather than assuming global root access, only escalate privileges for tasks that require it

### ISSUE THREAD

**Issue by colans** [geerlingguy/ansible-role-certbot#105]
Coming from #59 with a security perspective, it shouldn't be necessary to escalate privileges for the entire role.  It would be much safer to only do so for tasks that require it.

We can therefore update tasks like this:

```yml
- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"
```
...with this:

```yml
- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"
  become: true
```
...and then it wouldn't be necessary to apply `become: true` to the entire role invocation.
