### ISSUE TITLE
Starting tasks as a handler allows for more flexibility?

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-role-certbot#119]
Won't starting the web service in a handler allow for more flexibility?

I'm looking at the `start services after cert has been generated.` in `tasks/create-cert-standalone.yml`.

I've run into a catch-22.

The playbook I am working on I need the certificates generated but the apache service cannot be started yet. I need to do some additional configuring of apache. When this role attempts to start the apache service the service fails because my apache role (configuration) has not run yet.

If I move my apache role before the certbot role the apache server fails to start because the certificates have not been created.

Something like

`handlers/main.yml`
```yaml
- name: Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ certbot_create_standalone_stop_services }}"
```
`tasks/create-cert-standalone.yml`
```yaml
- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  notify:
    - Start services after cert has been generated.
  when: not letsencrypt_cert.stat.exists
```
