### ISSUE TITLE
'python-virtualenv' has no installation candidate

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-role-certbot#132]
The certbot package in Ubuntu 20.04 is too old to work with the ACME servers
```
acme.messages.Error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```
I changed to try to use certbot from source 
```yaml
certbot_install_from_source: true
certbot_repo: https://github.com/certbot/certbot.git
certbot_dir: /opt/certbot
certbot_version: master
certbot_keep_updated: true
```
The relevant error information is below
 
"msg": "non-zero return code"
"rc": 100
"E: Package 'python-virtualenv' has no installation candidate", "stderr_lines": ["E: Package 'python-virtualenv' has no installation candidate"]

Guessing it's the wrong package name?
```
$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

$ apt-cache search python | grep virtualenv
python3-virtualenv - Python virtual environment creator
```
Later in the output I see 
```
"Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
```
Can I get around this issue with the --no-bootstrap?

I'm guessing I'd need to override the certbot_create_command?

```
certbot_create_command: >-
  {{ certbot_script }} certonly --standalone --noninteractive --agree-tos
  --email {{ cert_item.email | default(certbot_admin_email) }}
  -d {{ cert_item.domains | join(',') }}
```
