### ISSUE TITLE
certbot-auto is being deprecated and does not work on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by smacz42** [geerlingguy/ansible-role-certbot#134]
Per https://github.com/certbot/certbot/issues/7941#issuecomment-619177149 the certbot-auto functionality is being deprecated and does not work on 20.04:

```

TASK [certbot : Generate new certificate if one doesn't exist.] ****************
--
21:34:37 |   | fatal: [hostname]: FAILED! => {
21:34:37 |   | "changed": true,
21:34:37 |   | "cmd": [
21:34:37 |   | "/opt/certbot/certbot-auto",
21:34:37 |   | "certonly",
21:34:37 |   | "--standalone",
21:34:37 |   | "--noninteractive",
21:34:37 |   | "--agree-tos",
21:34:37 |   | "--email",
21:34:37 |   | "user@example.com",
21:34:37 |   | "-d",
21:34:37 |   | "example.com"
21:34:37 |   | ],
21:34:37 |   | "delta": "0:00:00.030074",
21:34:37 |   | "end": "2020-12-02 02:34:37.844875",
21:34:37 |   | "rc": 1,
21:34:37 |   | "start": "2020-12-02 02:34:37.814801"
21:34:37 |   | }
21:34:37 |   |  
21:34:37 |   | STDOUT:
21:34:37 |   |  
21:34:37 |   | Skipping bootstrap because certbot-auto is deprecated on this system.
21:34:37 |   | WARNING: couldn't find Python 2.7+ to check for updates.
21:34:37 |   | Your system is not supported by certbot-auto anymore.
21:34:37 |   | Certbot cannot be installed.
21:34:37 |   | Please visit https://certbot.eff.org/ to check for other alternatives.
```

**Comment by smacz42** [comment]
This happens when called with `certbot_install_from_source: False` on Debian systems. Right now it looks like the certbot version is `0.27.0-1` in the ubuntu repos.

**Comment by sermo-de-arboribus** [comment]
This also happens with `certbot_install_from_source: True`

The new recommended way of installing certbot is explained in this thread: https://community.letsencrypt.org/t/certbot-auto-no-longer-works-on-debian-based-systems/139702/7

**Comment by Blake-** [comment]
From the new recommended way. 

```
How do I install Certbot now?
The way we recommend most users install Certbot is through snaps.
```

I'm not a big fan of snaps, but I guess that means a new task `install via snap` ?

**Comment by willemdh** [comment]
Similar issue for CentOS 8. IETF also recommends snap as install method apparently.. 😕

**Comment by mikejw** [comment]
I've made some progress with this issue, where cert rewnew is working fine but initial cert creation does not work.

First of all I have these additional steps in my playbook:

```
# install snap certbot
- hosts: build
  vars:
    env: "{{ (my_env is not defined or my_env is none) | ternary('build', my_env) }}"
  tasks:
    - name: set correct user
      set_fact:
        ansible_user: "admin"
      when: env == "build"
    - name: Install pip etc
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - snapd
          - apache2
      when: env == "build"
    - name: "Install snap core"
      snap:
        name:
          - core
    - name: "Install snap certbot"
      snap:
        name: certbot
        classic: yes
```

I then use this config in the next block of tasks:

```
  vars:
    certbot_script: "/snap/bin/certbot"
    certbot_install_from_source: false
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"
    certbot_auto_renew_options: "--apache --quiet --no-self-upgrade --pre-hook='/home/{{ ansible_user }}/certbot-hooks.sh pre' --post-hook='/home/{{ ansible_user }}/certbot-hooks.sh post' --deploy-hook='/home/{{ ansible_user }}/certbot-hooks.sh deploy'"
    certbot_create_command: "{{ certbot_script }} --apache certonly --expand --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
    certbot_certs:
      - email: mike@ai-em.net
        domains: "{{ domains }}"
    certbot_create_if_missing: true
    #certbot_create_method: standalone
    certbot_admin_email: mike@ai-em.net
    certbot_create_standalone_stop_services: []
```

I then use the following command manually to create the first domain name ssl:

`/snap/bin/certbot --apache certonly --expand --noninteractive --agree-tos --email mike@ai-em.net -d mydomain.com`

I'm not sure why the `certbot_script` isn't picked up during creation as it tried to use `certbot` instead of `/snap/bin/certbot`.

**Comment by mikejw** [comment]
I've come up with this little workaround. It's hacky.  

Also remove any use of the `--standalone` flag in your commands.

I don't unerstand why the`certbot_dir` and `certbot_script` variables can't be overridden (on cert creation etc), so that's why I've done the following.

```
# install snap certbot
- hosts: build
  vars:
    env: "{{ (my_env is not defined or my_env is none) | ternary('build', my_env) }}"
  tasks:
    - name: set correct user
      set_fact:
        ansible_user: "admin"
      when: env == "build"
    - name: Install pip etc
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - certbot
          - snapd
          - apache2
      when: env == "build"
    - name: "Install snap core"
      snap:
        name:
          - core
    - name: "Install snap certbot"
      snap:
        name: certbot
        classic: yes
    - name: "Rename old"
      command: mv /usr/bin/certbot /usr/bin/certbot.old
    - name: "Create link"
      file:
        path=/usr/bin/certbot
        src=/snap/bin/certbot
        state=link
```
