### ISSUE TITLE
Ansible-lint warn [301] Commands should not change things if nothing needs doing

### ISSUE THREAD

**Issue by edouard-lopez** [geerlingguy/ansible-role-certbot#144]
I have a task:

```yaml
- name: Create Certificate for webapps
  command: "{{ certbot_create_command }}"
  notify: Reload Apache
  tags: [web, ssl]
```

But [`ansible-lint`](https://ansible-lint.readthedocs.io/) complains

	  WARNING  Listing 1 violation(s) that are fatal                                                                                                                                                                                         
	  [301] Commands should not change things if nothing needs doing

What conditional do you recommend?`
