### ISSUE TITLE
install-with-snap.yml fails in Raspbian

### ISSUE THREAD

**Issue by andresrcs** [geerlingguy/ansible-role-certbot#161]
```
- name: Enable classic snap support.
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
```

There is no `/var/lib/snapd/snap` in the installation I get on Raspbian, pardon the naive question but, is this link actually needed in Raspbian? I'm asking because I commented out this task and the process seems to have finished successfully but I'm worried about what the consequences of skipping the link creation could be.
