### ISSUE TITLE
Install from source is broken; certbot-auto no longer exists

### ISSUE THREAD

**Issue by Synchro** [geerlingguy/ansible-role-certbot#167]
I'm following the instructions for installing from source, and although it installs without showing any errors, I end up without a certbot or certbot-auto executable. The EFF docs say that [certbot-auto no longer exists](https://eff-certbot.readthedocs.io/en/stable/install.html#id8), but [your ansible config is looking for it](https://github.com/geerlingguy/ansible-role-certbot/blob/master/tasks/install-from-source.yml). After the role pulls the source repo, I'm not seeing an obvious executable anywhere in it, so I assume it needs some build step, though I've no idea what that is.

The reason I'm doing this is because my DNS provider (gandi.net) is not supported by default, and the certbot plugins for it do not work with snap. I have the feeling I may have to fall back to [installing from pip](https://pypi.org/project/certbot/), even though the EFF recommends against it.

**Comment by Synchro** [comment]
FWIW, this is what I've come up with as a working ansible config for installing from pip:

```yaml
- name: Install certbot system dependencies
  ansible.builtin.apt:
    package:
      - python3
      - python3-virtualenv
      - libaugeas0
    state: present
    update_cache: yes
  tags: certbot

- name: Install certbot from pip
  ansible.builtin.pip:
    name: certbot
    virtualenv: /opt/certbot
  tags: certbot

- name: Link certbot into path
  ansible.builtin.file:
    src: /opt/certbot/bin/certbot
    dest: /usr/bin/certbot
    state: link
  tags: certbot
```
