### ISSUE TITLE
override {{certbot_script}} not work

### ISSUE THREAD

**Issue by manuelgerber** [geerlingguy/ansible-role-certbot#169]
Hello everybody,

It does not work to override the {{certbot_script}} variable in renk-cron.yml.  I Have a fix for this problem. 

```

---
- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Certbot automatic renewal.
    job: "{{ certbot_auto_certbot_script }} renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"

```

Best regards
Manuel
