### ISSUE TITLE
Syntax Error on install-with-snap.yml'

### ISSUE THREAD

**Issue by ziegelstein** [geerlingguy/ansible-role-certbot#177]
The role seems to have some Syntax Error. Running the following example playbook:

```yml
---
- hosts: example_server
  become: true
  vars:
    certbot_install_method: package
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_hour: "5"
    certbot_create_method: standalone
    certbot_auto_renew_user: root
    certbot_certs:
      - email: example@mail.com
        domains:
        - cert.example.com
  roles:
    - geerlingguy.certbot
```

gives the following error

```sh
ERROR! couldn't resolve module/action 'snap'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/user/.ansible/roles/geerlingguy.certbot/tasks/install-with-snap.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Install certbot via snap.
  ^ here
```

I'm using Ansible 2.10 and the current ansible galaxy version of the role on Ubuntu 20. I haven't checked the role itself, yet.
