### ISSUE TITLE
Adding new domains to a cert_item does not work

### ISSUE THREAD

**Issue by esnalabu** [geerlingguy/ansible-role-certbot#187]
When adding a domain to an existing cert_item, the role does not generate a new cert with the updated domains:

For example going from this: 
```
certbot_certs:
  - email: janedoe@example.com
    webroot: "/var/www/html"
    domains:
      - example1.com
      - example2.com
```

to this:
```
certbot_certs:
  - email: janedoe@example.com
    webroot: "/var/www/html"
    domains:
      - example1.com
      - example2.com
      - example3.com
```

...does not work.

This is due to the check for [whether or not to generate certs](https://github.com/geerlingguy/ansible-role-certbot/blob/c6297ddebb59c281e3a048c6ae77946e2caec13a/tasks/create-cert-standalone.yml#L2) is only checking if there is a file with the correct name/path.

It might make sense to allow the user to "force" regeneration using a variable, or maybe the role could test for aliases in the certificates instead of just the existence of the file. In any event, the role should be able to _revoke_ the existing certificates after deleting and creating new ones.
