### ISSUE TITLE
Unable to install from Source

### ISSUE THREAD

**Issue by PriyankaPrakashChand** [geerlingguy/ansible-role-certbot#195]
I am trying to install certbot via ansible from source but I am facing the following error
![image](https://user-images.githubusercontent.com/53374732/231219061-ddf8a022-957c-452e-b671-c0aaef8fb6c9.png)
![image](https://user-images.githubusercontent.com/53374732/231219210-6bb07448-ef76-480b-bef6-9de61a93efe4.png)

```
- name: Main Play
  hosts: local
  become: true
  vars:
    admin_user: "{{ ansible_user }}"
    admin_user_dir: /home/{{admin_user}}/
    certbot_install_method: source
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user }}"
    certbot_create_method: webroot
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_create_if_missing: true
    certbot_hsts: true
    certbot_admin_email: zxxxxxxxxxxx@gmail.com
    certbot_testmode: true

    certbot_certs:
      - webroot: "/var/www/letsEncrypt/"
        domains:
          - travelerindubai.com
    pip_install_packages:
      - docker
      - docker-compose
  roles:
    - geerlingguy.git
    - geerlingguy.certbot
```

I think the issue is the value of certbot_script that is set in tasks> install-from-source.yml>  Set Certbot script variable.
where ` certbot_script: "{{ certbot_dir }}/certbot-auto"`

while the latest certbot files have been removed from certbots Github directory:
https://github.com/certbot/certbot/pull/8938 
can someone help explain/fix this?
