### ISSUE TITLE
Apache and Certbot

### ISSUE THREAD

**Issue by clanstyles** [geerlingguy/ansible-role-certbot#22]
How can I auto run certbot and apache on install & updates of the virtual machines?

I've added certbot and from source. But the issue is setting up apache with SSL and then actually running the config THEN running cert bot THEN running and setting up SSL.

```
apache_vhosts:
  # Additional properties:
  # 'serveradmin, serveralias, allow_override, options, extra_parameters'.
  - servername: "xxx.com"
    documentroot: "/var/www/html"

apache_vhosts_ssl:
  - servername: "xxx.com"
    documentroot: "/var/www/html"
    certificate_file: "/etc/letsencrypt/live/xxx.com/cert.pem"
    certificate_key_file: "/etc/letsencrypt/live/xxx.com/privkey.pem"
    certificate_chain_file: "/etc/letsencrypt/live/xxx.com/fullchain.pem"
```

This was the config I was going with (using your apache config too). But if you run w/ cert_file like that, it will crash because apache wont start w/o the file.
