### ISSUE TITLE
Make renew command configurable

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-certbot#37]
Right now the renew command that's able to be set for cron is not configurable:

```yaml
- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Certbot automatic renewal.
    job: "{{ certbot_script }} renew --quiet --no-self-upgrade"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
```

The options should be configurable, maybe using a `certbot_auto_renew_options` var.
