### ISSUE TITLE
renewal

### ISSUE THREAD

**Issue by adespain** [geerlingguy/ansible-role-certbot#55]
So currently this playbook does not handle renewal automatically since it is standalone only?

In the readme it says:
`These services will only be stopped the first time a new cert is generated.`

So when the cron job runs to renew, does it automatically reload my nginx config to load the new certs? or will the cron job fail if the nginx service is running at the time the cron job runs the renew?

**Comment by voronkovich** [comment]
@adespain, you're right, the cron job will fail. To solve this issue you can override the job (see https://github.com/geerlingguy/ansible-role-certbot/blob/master/tasks/renew-cron.yml):
```yml
- hosts: all
  become: true

  post_tasks:

    - name: 'Add cron job for certbot renewal (if configured).'
      cron:
          name: Certbot automatic renewal.
          job: "service nginx stop && {{ certbot_script }} renew {{ certbot_auto_renew_options }} ; service nginx start"
          minute: "{{ certbot_auto_renew_minute }}"
          hour: "{{ certbot_auto_renew_hour }}"
          user: "{{ certbot_auto_renew_user }}"

  roles:

    - name: geerlingguy.certbot
```

**Comment by adespain** [comment]
Also theis cron job runs as the ansible_user which is non root but by default that user doesn't have permissions to access the letsencrypt log and config directories after installation.  Is there an easier way to get the cron job to work besides adding a sudo to the cron job command?  What is the best way to get the cron job to run with the correct permissions?

**Comment by voronkovich** [comment]
@adespain,  Just set the `certbot_auto_renew_user` variable to the root.
```yaml
- hosts: all
  become: true
  vars:
    `certbot_auto_renew_user: root
```
