### ISSUE TITLE
Renewing when ports 80 and 443 are already in use

### ISSUE THREAD

**Issue by astorije** [geerlingguy/ansible-role-certbot#57]
I have set up this role for auto-renewal, but noticed a few days ago that the cron doesn't auto-renew correctly. When I dry-run, I see that it's because ports 80/443 are already in use. Is there a way to make auto-renew cron stop/restart service like what this role does when creating new certs?

Some context of my current setup, if this helps:

**In `requirements.yml`:**

```yaml
- src: geerlingguy.certbot
  version: 3.0.0
```

**In `playbooks.yml`:**

```yaml
- role: geerlingguy.certbot
  become: yes
  tags: certbot
```

**In my host vars file:**

```yaml
## https://github.com/geerlingguy/ansible-role-certbot

# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew_user: jeremie

# Parameters used when creating new Certbot certs.
certbot_create_if_missing: yes
certbot_admin_email: "{{ admin_email }}"
certbot_certs:
  - domains:
    - [redacted]

# Ubuntu 16.04 does not have certbot package.
# To install from source (on older OSes or if you need a specific or newer
# version of Certbot), set this variable to `yes` and configure other options.
certbot_install_from_source: yes
```

**When I run `/opt/certbot/certbot-auto renew --dry-run`** (as mentioned [in the README](https://github.com/geerlingguy/ansible-role-certbot/blob/master/README.md#certbot-certificate-auto-renewal)):

```
Requesting to rerun /opt/certbot/certbot-auto with root privileges...
[sudo] password for jeremie:
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/[redacted].conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for [redacted]
Cleaning up challenges
Attempting to renew cert ([redacted]) from /etc/letsencrypt/renewal/[redacted].conf produced an unexpected error: Problem binding to port 80: Could not bind to IPv4 or IPv6.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/[redacted]/fullchain.pem (failure)
```

**When I run `/opt/certbot/certbot-auto renew`:**

```
Requesting to rerun /opt/certbot/certbot-auto with root privileges...
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/[redacted].conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer None
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for [redacted]
Cleaning up challenges
Attempting to renew cert ([redacted]) from /etc/letsencrypt/renewal/[redacted].conf produced an unexpected error: Problem binding to port 443: Could not bind to IPv4 or IPv6.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/[redacted]/fullchain.pem (failure)
```
