### ISSUE TITLE
Permission denied: '/var/log/letsencrypt/.certbot.lock'

### ISSUE THREAD

**Issue by colans** [geerlingguy/ansible-role-certbot#90]
I've been seeing this coming from the daily cron job:

> Cron <username@somewhere.example.com> certbot renew --quiet --no-self-upgrade

```
The following error was encountered:
[Errno 13] Permission denied: '/var/log/letsencrypt/.certbot.lock'
Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
```

Seems like it was set up to run as the user, not root?

**Comment by colans** [comment]
I missed this initially.  The README states:
> By default, this role configures a cron job to run under the provided user account [...]

The run configuration didn't match whatever was in `/etc/cron.d/certbot` so it took me a while to reconcile:
* `/etc/cron.d/certbot`, which handles renewals, is supplied by the Debian package.
* This role installs a cron job in the user's crontab.
* That cron job, the crontab one, fails by default as it's run by the unprivileged user.

To fix generally, it's necessary to set `certbot_auto_renew_user: root`, which perhaps we should be doing by default (although I understand the security implications of forcing users to be explicit about this).  However, for Debian-based OSes, renewals should be skipped entirely as this is already handled.

### Workarounds

#### Debian-based OSes

Set the variable `certbot_auto_renew: false`.

#### Non Debian-based OSes

Set the variable `certbot_auto_renew_user: root`.

**Comment by evilhamsterman** [comment]
This is actually handled by Pull Request #80. Sadly getting PR through @geerlingguy is difficult because he has so many popular roles

**Comment by colans** [comment]
This is still an issue.

**Comment by evilhamsterman** [comment]
Still an issue with a PR still open to solve it

**Comment by evilhamsterman** [comment]
Same comment as I posted before

**Comment by colans** [comment]
:wave:

**Comment by drakkhen** [comment]
👋

**Comment by zeqk** [comment]
> However, for Debian-based OSes, renewals should be skipped entirely as this is already handled.

How is this handled for Debian-based OSes?

Thank you

**Comment by colans** [comment]
@zeqk The Debian package handles renewals on its own via the `/etc/cron.d/certbot` cron job.

**Comment by zeqk** [comment]
I release in Ubuntu the renewal is handled by systemd https://serverfault.com/a/879711

I check this with the command `systemctl list-timers --all`

And I also check the `/etc/cron.d/certbot` content

```
# /etc/cron.d/certbot: crontab entries for the certbot package
#
# Upstream recommends attempting renewal twice a day
#
# Eventually, this will be an opportunity to validate certificates
# haven't been revoked, etc.  Renewal will only occur if expiration
# is within 30 days.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew
```

In systemd the cerbot autorenew is configured in 

```
 /lib/systemd/system/certbot.service
/lib/systemd/system/certbot.timer
```

the original `/lib/systemd/system/certbot.service` had this content

```
[Unit]
Description=Certbot
Documentation=file:///usr/share/doc/python-certbot-doc/html/index.html
Documentation=https://letsencrypt.readthedocs.io/en/latest/
[Service]
Type=oneshot
ExecStart=/usr/bin/certbot -q renew
PrivateTmp=true
```

So I update the ExecStart line with this

```
ExecStart=/usr/bin/certbot renew --quiet --no-self-upgrade --pre-hook "service nginx stop" --post-hook "service nginx start"
```

I also made this ansible role 


```yml
---
  - name: Ensure stop nginx when cerbot renew
    lineinfile:
      path: /lib/systemd/system/certbot.service
      state: present 
      backup: yes
      regexp: '^ExecStart'
      line: 'ExecStart=/usr/bin/certbot renew --quiet --no-self-upgrade --pre-hook "service nginx stop" --post-hook "service nginx start"'

  - name: Reload certbot.service
    systemd: 
      name: certbot
      state: reloaded
```

If you think it is fine maybe you can include this tasks in the `ansible-role-certbot` role
