### ISSUE TITLE
Multiple domains and each cert per domain is not getting created.

### ISSUE THREAD

**Issue by adespain** [geerlingguy/ansible-role-certbot#95]
I may just have something in my playbook misconfigured, but when I run it the first cert gets created for the first domain but the other 2 never get created.  Can anyone help me figure out why?

```

---
# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user }}"
certbot_auto_renew_hour: 3
certbot_auto_renew_minute: 30
certbot_auto_renew_options: "--quiet --no-self-upgrade"

# Parameters used when creating new Certbot certs.
certbot_create_if_missing: yes
certbot_create_method: standalone
certbot_admin_email: email@example.com
certbot_certs:  
  - domains: 
      - zionspftest1.ddns.net
  - domains:
      - zionspftest2.ddns.net
  - domains:
      - zionspftest3.ddns.net

certbot_create_command: >-
  {{ certbot_script }} certonly --test-cert --standalone --noninteractive --agree-tos 
  --email {{ cert_item.email | default(certbot_admin_email) }} 
  -d {{ cert_item.domains | join(',') }}
certbot_create_standalone_stop_services:
  - nginx
  # - apache
  # - varnish

# To install from source (on older OSes or if you need a specific or newer
# version of Certbot), set this variable to `yes` and configure other options.
certbot_install_from_source: no
certbot_repo: https://github.com/certbot/certbot.git
certbot_version: master
certbot_keep_updated: yes

# Where to put Certbot when installing from source.
certbot_dir: /opt/certbot
```
Here is my task output:
```
TASK [certbot : include_tasks] ********************************************************************************************************
task path: /Users/bigtone/github/ansible-playbooks/shared-roles/certbot/tasks/main.yml:10
included: /Users/bigtone/github/ansible-playbooks/shared-roles/certbot/tasks/create-cert-standalone.yml for 52.13.207.16
included: /Users/bigtone/github/ansible-playbooks/shared-roles/certbot/tasks/create-cert-standalone.yml for 52.13.207.16
included: /Users/bigtone/github/ansible-playbooks/shared-roles/certbot/tasks/create-cert-standalone.yml for 52.13.207.16

TASK [certbot : Check if certificate already exists.] ***********************************************************************************
task path: /Users/bigtone/github/ansible-playbooks/shared-roles/certbot/tasks/create-cert-standalone.yml:2

ok: [52.13.207.16] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "checksum_algorithm": "sha1",
            "follow": false,
            "get_attributes": true,
            "get_checksum": true,
            "get_md5": null,
            "get_mime": true,
            "path": "/etc/letsencrypt/live/zionspftest1.ddns.net/cert.pem"
        }
    },
    "stat": {
        "exists": false
    }
}

TASK [certbot : Stop services to allow certbot to generate a cert.] *********************************************************************
task path: /Users/bigtone/github/ansible-playbooks/shared-roles/certbot/tasks/create-cert-standalone.yml:7

ok

TASK [certbot : Generate new certificate if one doesn't exist.] *************************************************************************
task path: /Users/bigtone/github/ansible-playbooks/shared-roles/certbot/tasks/create-cert-standalone.yml:14

changed: [52.13.207.16] => {
    "changed": true,
    "cmd": [
        "letsencrypt",
        "certonly",
        "--test-cert",
        "--standalone",
        "--noninteractive",
        "--agree-tos",
        "--email",
        "email@email.com",
        "-d",
        "zionspftest1.ddns.net"
    ],
    "delta": "0:00:06.326111",
    "end": "2019-10-15 19:27:13.472472",
    "invocation": {
        "module_args": {
            "_raw_params": "letsencrypt certonly --test-cert --standalone --noninteractive --agree-tos  --email email@example.com  -d zionspftest1.ddns.net",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2019-10-15 19:27:07.146361",
    "stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenticator standalone, Installer None\nObtaining a new certificate\nPerforming the following challenges:\nhttp-01 challenge for zionspftest1.ddns.net\nWaiting for verification.
..\nCleaning up challenges",
    "stderr_lines": [
        "Saving debug log to /var/log/letsencrypt/letsencrypt.log",
        "Plugins selected: Authenticator standalone, Installer None",
        "Obtaining a new certificate",
        "Performing the following challenges:",
        "http-01 challenge for zionspftest1.ddns.net",
        "Waiting for verification...",
        "Cleaning up challenges"
    ],
    "stdout": "IMPORTANT NOTES:\n - Congratulations! Your certificate and chain have been saved at:\n   /etc/letsencrypt/live/zionspftest1.ddns.net/fullchain.pem\n   Your key file has been saved at:\n   /etc/letsencrypt/live/zionspftest1.ddns.net/privkey.pem\n   Your ce
rt will expire on 2020-01-13. To obtain a new or tweaked\n   version of this certificate in the future, simply run certbot\n   again. To non-interactively renew *all* of your certificates, run\n   \"certbot renew\"\n - Your account credentials have been saved in your Ce
rtbot\n   configuration directory at /etc/letsencrypt. You should make a\n   secure backup of this folder now. This configuration directory will\n   also contain certificates and private keys obtained by Certbot so\n   making regular backups of this folder is ideal.",
    "stdout_lines": [
        "IMPORTANT NOTES:",
        " - Congratulations! Your certificate and chain have been saved at:",
        "   /etc/letsencrypt/live/zionspftest1.ddns.net/fullchain.pem",
        "   /etc/letsencrypt/live/zionspftest1.ddns.net/privkey.pem",
        "   Your cert will expire on 2020-01-13. To obtain a new or tweaked",
        "   version of this certificate in the future, simply run certbot",
        "   again. To non-interactively renew *all* of your certificates, run",
        "   \"certbot renew\"",
        " - Your account credentials have been saved in your Certbot",
        "   configuration directory at /etc/letsencrypt. You should make a",
        "   secure backup of this folder now. This configuration directory will",
        "   also contain certificates and private keys obtained by Certbot so",
        "   making regular backups of this folder is ideal."
    ]
}
