### ISSUE TITLE
Certbot only create 1st domain!

### ISSUE THREAD

**Issue by chithanh89** [geerlingguy/ansible-role-certbot#96]
Hi guys,

I use this playbook to generate cert, i want to create 3 domain cert but when running,only 1st domain created.
certbot_certs:
 - email: x@x.com
   domains:
     - a
     - b
     - c
I must run 3 times to create 3 cert for each domain, how can i run only 1 but still create 3 domain?
Thank you!

**Comment by widhalmt** [comment]
Hi.

I just encountered the same problem by only using the global e-mail address. Is there a solution by now?

Cheers,
Thomas

**Comment by IyadKandalaft** [comment]
This is not an issue and it works as designed.  Adding 3 domains under the same task will put them as SANs under the sam certificate.

I didn't validate the following but it might work:
```
- email: abc@123.com
  domains:
    - mydom1.com
- email: abc@123.com
  domains:
    - mydom2.com
- email: abc@123.com
  domains:
    - mydom3.com
```
